version: "3.8"
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=tischify
      - POSTGRES_PASSWORD=tischify
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
